server:
  tomcat:
    uri-encoding: UTF-8
    connectionTimeout: 200000
  port: 8080
#  servlet:
#    context-path: /geeklife

spring:
 # druid数据源
  datasource:
    url: jdbc:mysql://172.16.54.173:3306/ledao_strs?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Mysql3321%
    name: LD_DirectRent
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# redis
  redis:
    host: 172.16.54.173
    port: 6379
    password: '!RE%^E332^3ZDWEwwwe7839'

#mybatis配置
mybatis:
  type-aliases-package: com.geek.life.model.pojo
  mapper-locations: classpath:mappers/*.xml

# 分页工具
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 是否开启swagger
swagger:
  show: true